import "../../styles/colors.css";
import "../../styles/fonts.css";
import "../../styles/globals.css";

export const metadata = {
  title: "UX by Lou",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
