import "../../styles/colors.css";
import "../../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <header>Lous Landing page</header> */}
        {children}
        {/* <footer>© 2025 Lou Hedberg</footer> */}
      </body>
    </html>
  );
}
